url: "https://fqm365.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "FQM-365" # the name of your site, e.g. ACME Corp.
description: "Official FQM-365 research group webpage"
theme: academic-jekyll-theme
